### ISSUE TITLE
Image persists from cloned object until saved a second time

### ISSUE THREAD

**Issue by aksm** [esmero/strawberryfield#151]
Not sure if this is expected behavior, but when I clone an object, remove the image from the original object, attach a new image, and save as the new object, both images persist. If I save the object a second time, the original image disappears and only the new image remains.

**Comment by DiegoPino** [comment]
@aksm now that this is here: this is the issue

https://github.com/esmero/strawberryfield/blob/026847c1210e18d60e5c76c21f75f62a4d8a2633/src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php#L149-L153

I assumed (wrongly as I notice now) that new entities have  no `as:image`, `as:document` , etc JSON structures yet so do not need those to be cleaned up because file adding and removing at that stage (new) only generates changes in the actual JSON Keys that are fed by the "upload" elements.

But! When you clone an object, the already existing ones are brought over but its also marked as "new". So I skip cleaning that up

All this was made to avoid over processing but clearly I can not skip this test

Solution:

A bit more processing will be needed
Pseudo Code will be:

- For new entities only do expensive processing if `as:image` etc is there (that will make new Objects faster to process)
- If as:structures are there
  -  For each as:structure, check their `dr:for`key. If dr:for exists then check if the key still contains the File ID. If not, remove.

Since File persistence is quite important in Digital Repositories and I do not want (by mistake) loose a file, I will have to do some test+extra test on this. Still a few hours left before fixed!

Thanks @aksm, marking this as a Bug and will let you know when the pull is in.

**Comment by DiegoPino** [comment]
@aksm a pull is in, if you want to test.
https://github.com/esmero/strawberryfield/pull/152

Simplest way may be to go to your `archipelago-deployment` folder:
```SHELL
cd web/modules/contrib/strawberryfield
sudo git fetch
sudo git checkout ISSUE-151
```

Test and let me know if saving is working. This is a larger refactor but it feels I got it this time right.

**Comment by aksm** [comment]
That did the trick! Amazing work as always. Thanks!

**Comment by DiegoPino** [comment]
Thanks to you @aksm!! We will merge this into RC2 tomorrow once testing is done

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/strawberryfield/commit/a489f68fd2c46c69bb6aaaeeb9d00bced8c82fd6
