### ISSUE TITLE
Flavor docs come back to Solr after untracked after some minutes

### ISSUE THREAD

**Issue by giancarlobi** [esmero/strawberryfield#169]
@DiegoPino The base environment I used to check: Drupal  9.1.5, search_api:1.x-dev, Cron manually configured
The steps to reproduce the issue:
- Clear Solr indexing, rebuild tracking, index
Strawberryfield Flavor Datasource (0/0 indexed)
No flavor docs on Solr
- Add ADO pdf 4 pages (by webforms)
- Run CRON
Background queues executed
Strawberryfield Flavor Datasource (0/4 indexed)
- Index
Strawberryfield Flavor Datasource (4/4 indexed)
Solr: 4 flavor docs
No search_api errors in dlog
ADO IAB search works
- Edit ADO by webforms, remove pdf4 and add pdf13
After last SAVE error in dlog:
Drupal\Core\Entity\Query\QueryException while attempting to find indexed entities referencing changed Content with ID "122" for index Drupal Content to Solr 7: Invalid specifier 'sbf_entity_reference_ismemberof' in Drupal\Core\Entity\Query\Sql\Tables->addField() (line 306 of /var/www/archipelago/web/core/lib/Drupal/Core/Entity/Query/Sql/Tables.php).
- Before run CRON
Strawberryfield Flavor Datasource (0/0 indexed)
Solr: no flavour docs
- Run CRON
Queues (1+13) runned
No errors in dlog
Strawberryfield Flavor Datasource (0/13 indexed)
Solr: no flavour docs
- **Wait 5 minutes, 4 flavor docs appear again in Solr**
BUT Strawberryfield Flavor Datasource (0/13 indexed)
- Index
Strawberryfield Flavor Datasource (**13/13 indexed**)
Solr: **17 flavor docs** (4+13)

**Comment by giancarlobi** [comment]
The Solr log regarding 4pages (first indexing, delete, re-indexing):
`2021-03-26 15:32:59.848 INFO  (qtp1997859171-234) [   x:archipelago] o.a.s.u.p.LogUpdateProcessorFactory [archipelago]  webapp=/solr path=/update params={json.nl=flat&commitWithin=1000&omitHeader=false&wt=json}{add=[g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:1:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309134367293440), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:2:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309134389313536), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:3:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309134393507840), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:4:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309134397702144)]} 0 37`

`2021-03-26 15:38:36.952 INFO  (qtp1997859171-251) [   x:archipelago] o.a.s.u.p.LogUpdateProcessorFactory [archipelago]  webapp=/solr path=/update params={json.nl=flat&commitWithin=1000&omitHeader=false&wt=json}{deleteByQuery=_root_:("g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:1:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr" OR "g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:2:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr" OR "g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:3:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr" OR "g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:4:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr") (-1695309487863234560),delete=[g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:1:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (-1695309487880011776), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:2:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (-1695309487881060352), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:3:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (-1695309487881060353), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:4:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (-1695309487881060354)]} 0 17`

`2021-03-26 15:43:40.647 INFO  (qtp1997859171-245) [   x:archipelago] o.a.s.u.p.LogUpdateProcessorFactory [archipelago]  webapp=/solr path=/update params={json.nl=flat&commitWithin=1000&omitHeader=false&wt=json}{add=[g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:1:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309806296891392), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:2:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309806315765760), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:3:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309806319960064), g0qa5y-default_solr_index-strawberryfield_flavor_datasource/122:4:en:32a2b020-809f-4d84-b5f2-c6e55da51f97:ocr (1695309806323105792)]} 0 32`

**Comment by DiegoPino** [comment]
@giancarlobi thanks a lot. I will check, correct and commit and will also let you know. Hugs

**Comment by giancarlobi** [comment]
@DiegoPino I couples of notes more:
- it also happens with new Archipelago, search_api 1.19 and without last PR regarding plaintext
- the solr docs that come back have a timestamp 10 minutes (in both check I made) before the second ones, exactly 10 minutes.

**Comment by DiegoPino** [comment]
@giancarlobi I did some tests with the mono Hydroponics processor and I could only replicate the issue once.
In most of the cases the Solr Documents get removed and never come back, except if, there is a racing condition between enqueued items, still in process items and the deletion Event Subscribers (FYI I added a second one that deals with Full ADO deletion if you want to test that)

The issue seems to be the following:

In every case we are going to add to the Tracker and then the Tracker requests from the Datasource the ID there is something in common, the File Entity in question exists and/or the Flavor for that Document is not returned (yet) from a Solr Query when checking the IDs that exist. The former is right since we do not delete files (on purpose), we just remove its usage count, that way users can revert and existing ADO revision and get back to a previous state. The fact that you can revert means also a new Save event occurs.

How to fix that case?

There are a few options:
1.- Not only remove from the tracker and Solr but also remove from the Key Value (temporary storage) which is used by the Data Source when a Load Multiple is requested. Worst case scenario if we request if again there it will fail and Search API will assume its not longer available, throw and Log Message and desist trying to track it again (until retracked of course)
2.- Not only check if the File in question exists (the PDF that generated the HOCR) but also if the Current Revision of the ADO still holds that File. This adds extra processing and I wonder if you are Ok with just the first option?

In any case non of this adds a new issue, it just maintains an existing issue we already had.

Also, regarding exception the Logs we saw after upgrading Search API to 1.19 and 1.x-dev. I opened a Drupal ISSUE here:
https://www.drupal.org/project/search_api/issues/3205968

I tried to explain our issue as good as possible (and as polite as possible). I marked the issue as a feature request (which I can fulfill if my approach makes sense to people). The problem of course is that via an EntityQuery (drupal wrapper for an SQL query) the exposed JSON Key value properties we use to index related objects can not be accessed because they are not accessible like that in the DB (and as we know Drupal has no JSON SQL support). My proposed solution is that we can "attempt" in that failure case to use the already indexed Entities to fetch which other Entities are referencing a given ADO instead of using SQL. But I know its an edge case. Second proposed solution is to introduce an Event there so we, in our implementation can Write a Subscriber that does exactly that.

In the meantime I will resolve the issue you are seeing using 1.- option one and we can go from there. Thanks a lot!

**Comment by giancarlobi** [comment]
@DiegoPino Great! I made some checks adding/changing PDF with others and all works well. The right number of pages/flavor appear as indexed and also in Solr and no more removed flavors come back. So for me this is solved, I'll close this issue. Thanks friend!!
