### ISSUE TITLE
Access to strawberryfield_flavor_datasource data disabled for anonymous

### ISSUE THREAD

**Issue by giancarlobi** [esmero/strawberryfield#170]
@DiegoPino In a Views, when we have to access data of strawberryfield_flavor_datasource, I have to config advanced query settings to by-pass permission check if not anonymous can't see view results.

**Comment by DiegoPino** [comment]
Thanks @giancarlobi 
Looking at it: All that magic happens in the Access Control Processor: 
\Drupal\search_api\Plugin\search_api\processor\ContentAccess

I will look at how our `strawberryfield_flavor_datasource` deals (at $item) level with giving the Processor the data it needs to index the right Values. Thanks!

**Comment by DiegoPino** [comment]
@giancarlobi in the meantime. If you disable the "Access Control" Search API Processor, SBF access control is respected correctly. I will build eventually a Processor just for this, but it seems to be that the Access Control processor adds more burden. Why? Because without it, by just changing the Status (e.g to Archived) to an ADO that generated HOCR, SBF respects that and stops appearing immediately from Views without reindexing. With the Processor (and if I fix it) it would require a reindex.

Only benefit I see of the processor is that it would return "less" Documents for the same query. Give it a try if you have time

**Comment by giancarlobi** [comment]
@DiegoPino Friend, if I have some time this weekend I'll check this, to be clear, is this the UI where I have to disable "Access Control" Search API Processor?
![image](https://user-images.githubusercontent.com/4232178/113479498-c28a2680-948f-11eb-9647-1a5f2ec02f81.png)

**Comment by DiegoPino** [comment]
@giancarlobi sorry for the delay, got distracted with life and code (AMI). Yes, that is the checkbox. Once you disable, reindex. The behavior I saw is that Views will respect Entity Access and since SBF are exposed as "nodes" even if they are not, if an ADO that produced them can not be seen by a certain user (because its Archived, draft or Access Control does not allow that user to see it), also OCR (pages) will be hidden.

Please give it a look and let me know if you see the same behavior.
The only down site (means I will eventually build that processor, I promise) is that the query itself will generate results (all the ones that would match) and it is Drupal Views and core Access Control that filters them out. That may have performance issues, but since there is also paging happening, maybe not that bad? (at least until I code the whole thing).

Thanks a lot and again sorry. Coding as fast as I can!

**Comment by giancarlobi** [comment]
@DiegoPino On one archipelago that works fine:
- I restored default views query settings (unflagged by pass access control)
- I disabled access control processor as above image
- Searching works fine: if published node and flavors returned, if draft/archived nothing returned
Only a collateral note: after change draft-published-archived I have to drush cr to reflect status iin search result, probably due some type of cache or other settings.
I'll check now in the second archipelago and report here, friend

**Comment by giancarlobi** [comment]
I forgot, I merged in my git and updated archipelago with SBF ISSUE-171 and SBR ISSUE-34

**Comment by giancarlobi** [comment]
@DiegoPino Also on the second archipelago it works fine, anonymous can view (as search result) node and flavors only if parent node is published. 
Also in this case I need a drush cr to reflect node status in search result.

**Comment by DiegoPino** [comment]
Hi
> Searching works fine: if published node and flavors returned, if draft/archived nothing returned
Only a collateral note: after change draft-published-archived I have to drush cr to reflect status iin search result, probably due some type of cache or other settings.

Views have different cache settings, the one I feel works best for Solr driven ones is:
![image](https://user-images.githubusercontent.com/6946023/113713872-ce573200-96b5-11eb-884a-06f2385c69b2.png)

`Search API tag based`

In general, for a production machine I would discourage a full `drush cr` but during development to test code it is fine  (and recommended). If you have stuck caches of rendering I would recommend always `drush cache:clear render`

**Comment by giancarlobi** [comment]
@DiegoPino With caching set as you suggest it works fine.
As all checks were good, for me we can close this issue, feel free to close as you want.

**Comment by DiegoPino** [comment]
Thanks! Will close once I get the pulls merged. Thanks again for opening it, debugging and testing!!!

**Comment by DiegoPino** [comment]
Closing this since its solved. Thanks!!

**Comment by DiegoPino** [comment]
@giancarlobi reopening this since having the processor disabled does not work well with facets on the long run and also displays wrong number of results count even if the actual nodes are not displayed in the View (at least that is good). I will open a new issue for this and document it.

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/strawberryfield/commit/1d1cff16f3bde4d6da06a156f8e9306551388e87
