### ISSUE TITLE
EDTF Date Strawberryfield Key Name provider

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberryfield#175]
Need a way to index EDTF date strings as dates in solr. This document captures the issues/complexity, I think: https://lyrasis.zendesk.com/hc/en-us/articles/360041734211-Deep-dive-Best-practices-for-dates-in-Islandora-MODS-metadata

@DiegoPino I could not find another github issue for this, but if there is, feel free to close this one and let me know where it is. I'm willing to have this task assigned to me if I can grab some time with you to get me pointed in the right direction.

**Comment by DiegoPino** [comment]
@patdunlavey good. There is no other one specific to this one open (there is a global mention of a date aware one but this is better).

My guts here:
1.- ISO8601 is a subset of ETDF so we need only a single Key Name Provider and the key name provider does not need to know the source/format selected.
2.- Key Name providers are optimistic and opportunistic. They will try to provide data in the chosen TypeData format but if that is not possible they should return empty (not failure).
3.- Key Name provider should be Solr Date Range aware and provide the proper format. But if so, then the output should be only for Ranges since the Solr Field assigned at the Search API level needs to match one type only. Means if you need point and ranged dates you need to configure two key name providers with different settings. Means also parsing ranges/points needs to be a setting
4.- Human readable expression should be also an option. If selected the output format will be string. 
5.- You can also test outputting always strings, just with the right format. Search API should be able to cast them if the format is right to a date (would mean a less complex Key Name provider too)

Hope this helps. I would use the https://github.com/esmero/strawberryfield/blob/1.0.0-RC2/src/Plugin/StrawberryfieldKeyNameProvider/JmesPathNameProvider.php or even extend it as base class. Since it includes already the "get value via JMESPATH and get multiple JMESPATHS as a single one" functionality

**Comment by DiegoPino** [comment]
Solved vy https://github.com/esmero/strawberryfield/commit/79f30cd791c569954c299a4cc158d4f8c2b0580d and https://github.com/esmero/strawberryfield/commit/13a20d31a12a6c79bf800bd9502f467667ca3af2

The JmesPath provider now supports most Date strings, including ISO8601, free text cast-able to DateTime and EDTF individual and range formats. The key name provider has a checkbox that enables this logic. If the value does not match the returning value will be NULL
