### ISSUE TITLE
Make digital object storage folder configurable

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberryfield#196]
# What

The file persister destination folder for digital object files is hard-coded in [StrawberryfieldEventInsertSubscriberDepositDO->onEntityInsert()](https://github.com/esmero/strawberryfield/blob/main/src/EventSubscriber/StrawberryfieldEventInsertSubscriberDepositDO.php#L122) to `://dostorage`. I don't see any place where this can be altered.

In our case, we want to store digital object files for staging and production into separate folders while still using the same s3 bucket. 

# Possible solutions
1. Modify the path construction logic so that the `://` is stored as part of the `strawberryfield.storage_settings.object_file_scheme`. This would require a change in the code that stores the object_file_scheme, as well as the code that reads it. Then a form alter could be written targeting the FilePersisterServiceSettingsForm storage schema options, providing different options for staging and production.
2. Add an alter hook immediately or soon after the above referenced line where $path is defined. I'll note that an alter hook is provided for `StrawberryfieldFilePersisterService::getDestinationUri`, so consistency would argue for this as the preferred option. 
3. Actually make the storage folder configurable on the file persistence settings form. Add a text field labeled "Storage Path for Persisting Digital Objects", with the default value "dostorage", but where one could enter e.g. "production/dostorage".

@DiegoPino, I'll be happy to send you a PR for whatever solution you think makes most sense.

**Comment by DiegoPino** [comment]
@patdunlavey yes, it can not be altered right now. I think keeping the scheme around as it is (so not adding the ://) + adding a secondary "folder/prefix" option/form element/setting may be Ok. And either a hook (which may all disappear by Drupal 10) or Emmitt a Symfony event other modules can use (with a subscriber) to alter the $path too. The event is the preferred way and SBF will eventually get refactored to use an event too (no worries, won't remove the alter hook) for modifying the file persistence part.

Happy to review a Pull request (which reminds me please check your code review on the XDEBUG documentation which has unanswered change requests coming from the team). 

For the pull please check https://github.com/esmero/strawberryfield/pull/189/files since there is also a new mode there which adds a new Eventsubscriber for the same purpose. Thanks!

**Comment by patdunlavey** [comment]
I need to learn the event subscriber system, so I'll give that a whirl. Do you not like the third option (just provide configurability of the folder path(s) on the form, and don't require a developer intervention (hook or even subscriber)?

**Comment by DiegoPino** [comment]
@patdunlavey I like the third option! (but not storing the :// in the config) but I also see how someone may would like to totally alter the path

**Comment by patdunlavey** [comment]
PR for third option: https://github.com/esmero/strawberryfield/pull/198

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/fccd0402ef5e72605b6e3e9b28bade9118943bd2
