### ISSUE TITLE
Immediate garbage collection of temporary files after metadata generation?

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberryfield#204]
We've run into a problem testing ingests of large movie files where the esmero-php container's /tmp directory fills up and then the process crashes. This is not related to the Drupal file system "Delete temporary files after..." setting, I don't think? 

Is there a reason not to immediately delete the file from the temporary:// directory after metadata has been generated? I see that there is logic that tests to see if the file already exists in the temporary directory prior to making a new copy, and I suppose the purpose of this is to make re-processing an ami set more efficient. But that gain is at the cost of potentially vast amounts of disk space on the php container. 

# Possible solution?:
1. Add `$file_is_temporary_copy = TRUE`; just after the file copy operation at
https://github.com/esmero/strawberryfield/blob/d99610800405ae2fc60c166c88bbe1c72503a942/src/StrawberryfieldFilePersisterService.php#L1287

2. Just before `return $metadata` at https://github.com/esmero/strawberryfield/blob/d99610800405ae2fc60c166c88bbe1c72503a942/src/StrawberryfieldFilePersisterService.php#L1596
, put something like 
```
if(!empty($file_is_temporary_copy) && !empty($templocation) {
      $this->fileSystem->unlink($templocation);
}
```

**Comment by DiegoPino** [comment]
Sorry but I told you so. I need more info. What do you mean with large size, where are those files located before the ingest? If this is a need this needs to be a toggle/options not a core change because having files persist for the normal amount of a temp lifespan is part of the design. Not sure if the toggle should be at AMI set level (e.g during the processing) or a global one. But I told you that disabling temporary file removal had consequences.

Lastly, this can also (and should) be dealt as a devops issue. /tmp or any temporary folder you assign to Drupal can be an external mount/docker mount. And you could have a special/cheap/magnetic drive of 1TB to deal with this if needed. I'm not going to say no to this request, but I think there needs to be a proposal that covers a larger community need and has huge files low tmp as an exception/decision. Happy to help to figure out how to address this. Thanks!

**Comment by DiegoPino** [comment]
Also note: having temporary files persist longer is needed because of Post Processing/Exif and Media Info extraction. So knowing the size/demo files we can do some test cases and see/figure out the sweet point.

**Comment by patdunlavey** [comment]
Thanks Diego. Forgive my ignorance (as always!), but I don't understand how the Drupal temporary file management policy impacts these files. I don't think these are managed files and therefore are not tracked by Drupal. You did warn of the dangers of configuring "Delete temporary files after" to "Never", but I think in that thread we determined that disabling Drupal's temporary file management as the only safe option we have since our S3 file store is our permanent repository for our files, and we can't have Drupal deciding to delete them under any circumstances. Better for us to deal with the other non-ADO files manually (in our case we settled on using the auditfiles module to simplify management of these files).

The code I proposed to change is entirely inside the StrawberryfieldFilePersisterService::getBaseFileMetadata method. You mentioned other post processing actions, but I only see this method called from StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator::onEntityPresave. In any case, even if I missed something, the worst case scenario is that this method would need to copy the file to the temp directory again. Am I wrong?

These files are in S3, as I mentioned earlier and that's where they stay. The AMI ingest set that we are testing is a couple hundred movies, whose files total a couple hundred gigabytes. The only safe method of purging the /tmp directory is to restart the containers since we cannot know otherwise if deleting the file would impact a currently running process. Restarting the container does not seem like an elegant way to manage a runaway /tmp file directory when the process creating those files is the one that can know when it's safe to delete them. But expanding disk capacity in a  huge way to store for files that don't actually need to be kept around doesn't seem to make sense to me. We can do it though, if that's the best solution. 

Are you saying, after my obnoxious arguing with you, that you're convinced that simply expanding disk space and planning to restart containers periodically is our best option?

**Comment by DiegoPino** [comment]
Pat, sorry I totally did not meant to suggest restarting a container was even an option. Let's make this issue a more global one and let's have a call (I can tomorrow 1PM or 3PM): More global one means: audit and deal with file/garbage clean up globally as a service in archipelago. The issue here is a performance v/s space issue. Performance in the sense that temporary files "may" be reused when accessed locally because you can not run Checksum or EXIF extractions on S3 driven files. You need to have them locally. My suggestions as a workaround is to deal with this correctly as DevOps. and treat the /tmp clean up (again in the meantime) as a tasks like a UNIX system deals with it. Cleaning on accessed files in a certain period. But the /tmp becomes a mount replacing the internal /tmp that the container provides. Which is one of the big advantages of Docker that you can replace any internal path by an external driven one. Please put something in my agenda. I'm very much happy to tackle this issue but not as a specific use case need but as a global impact task that allows also future growth/compat (e.g for Strawberry Runners). Hope this makes sense, I know my replies read sometimes as a NO. They are never NOs, just other ways and happy to be convinced and show how we can make all better. Again thanks for your issue and the use case.

**Comment by patdunlavey** [comment]
Thanks Diego. As always seems to happen, what seems like a simple problem to solve turns into a brain-bender! I'll take a look at the strawberry_runner module. 

Unfortunately, I plan to be out tomorrow afternoon. If you think a call is necessary, can you propose another time?

**Comment by patdunlavey** [comment]
Update @DiegoPino: I can do a call at 1:00. I'll be out at 2:00.

**Comment by DiegoPino** [comment]
Ok, cool. Will send a zoom invite tomorrow morning for 1PM. thanks a lot!

**Comment by DiegoPino** [comment]
@patdunlavey commit into open #189 coming tomorrow afternoon. Hopefully we can merge by Thursday morning

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/494d522f2dce79c202e533b72582c8b1829eb9af
