### ISSUE TITLE
Write entity labels into JSON for the Webform "Entity reference elements"

### ISSUE THREAD

**Issue by fishfree** [esmero/strawberryfield#284]
![image](https://github.com/esmero/strawberryfield/assets/1741341/2e715dae-5d7c-4fcd-ab3d-581063658fcd)
For the elements above, strawberryfield can only write the entityid into JSON:
![image](https://github.com/esmero/strawberryfield/assets/1741341/acfa737b-1154-4aad-ad16-49ba1e78ca73)

If the entity label can also be written into the JSON, then we can use them later in` Strawberry Key Name Providers `and other scopes.

**Comment by fishfree** [comment]
@DiegoPino Hello, Diego, could you have a look at this issue, please? I think my issue is significant for extending meta-data description for ADOs.

**Comment by DiegoPino** [comment]
@fishfree I thought I had answered this, this not really an issue. Also, not something that makes sense changing since its a Drupal integration (you want to have numbers BC then how will webform now when "editing" what the original taxonomy ID you saved was?)

In archipelago _You_ can use Key Name providers already to convert ANY entity type (using any Numeric ID value present in your JSON) natively (for Solr or the rest of the Drupal environment) and thus index just the label/facet, etc.

Side note: Using Taxonomies is (for portability, replication, stability and also Linked Open Data) really not a recommended way for Metadata/cataloging/libraries and museums. E.g, What if someone deletes a taxonomy? What if someone changes it?What if you have to recreate your taxonomies in another repository and your IDs change?
That is why we encourage to use real Vocabularies from external public sources that bring back stable URIs and labels (a time/specific in time snapshot of what a cataloger saw) of a reality, but since we do have users using taxonomies already AND **key Name providers** already have the capacity of converting/extracting etc for Solr what you need, you can do this if WIKIDATA, LoC, VIAF, GETTY are not good for your need.

Here is a screenshot of "ismemberof" keyname provider using the NODE ID to load an entity. Same can be done for Taxonomies.

![image](https://github.com/esmero/strawberryfield/assets/6946023/054b0f9f-9783-4242-885a-6039e7c8e5f3)

**Comment by fishfree** [comment]
@DiegoPino Thank you for your tip! It becomes clear to me now. I guess, in order to make my expectation, I need:

1. Add a key name provider like ismemberof on page /admin/structure/strawberry_keynameprovider/add;
2. Add a metadata display with Twig on page /metadatadisplay/add;
3. On page /admin/structure/types/manage/digital_object/display, set the ADO strawberry field with formatter `Strawberry Field Formatter for Custom Metadata Templates`, and select the metadata template created in the second step.

However, I'm stuck on the second step. I don't konw how the exact variable name of the data from the keynameprovider created in the first step. Could you help me please?

**Comment by DiegoPino** [comment]
Closing as resolved
