### ISSUE TITLE
Escape tags on the default raw json formatter

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#303]
@alliomeria maybe this is one you could tackle during the week? Same json argument we tested live with good results on Friday.Please ping me if you decide so(or if not too). For 1.4.0. Thanks!

**Comment by alliomeria** [comment]
Hello @DiegoPino, following up on our live discussion from earlier today, since you are going to do the pull for code... I'll make a PR for the [corresponding template updates from my local deployment fork](https://github.com/esmero/archipelago-deployment/compare/1.3.0...alliomeria:archipelago-deployment:1.3.0) if that sounds ok to you. Let me know what you think. Thank you! :)

**Comment by DiegoPino** [comment]
Thanks for the template update. Will close this ticket once you have that.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/b6f56be08f16b0ecda0abc97e4bcbd1de6bf6372 and via template update by @alliomeria via https://github.com/esmero/archipelago-deployment/commit/4a381851debb9ebac938bbc34e2467747700d15d
